# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_stub_pb2 as grpc__stub__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_stub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MainRouterStub(object):
    """Implemented by the Main Service — receives messages forwarded by CM workers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteInboundMessage = channel.unary_unary(
                '/MainRouter/RouteInboundMessage',
                request_serializer=grpc__stub__pb2.InboundMessage.SerializeToString,
                response_deserializer=grpc__stub__pb2.RoutingAck.FromString,
                _registered_method=True)


class MainRouterServicer(object):
    """Implemented by the Main Service — receives messages forwarded by CM workers
    """

    def RouteInboundMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainRouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteInboundMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteInboundMessage,
                    request_deserializer=grpc__stub__pb2.InboundMessage.FromString,
                    response_serializer=grpc__stub__pb2.RoutingAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MainRouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MainRouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MainRouter(object):
    """Implemented by the Main Service — receives messages forwarded by CM workers
    """

    @staticmethod
    def RouteInboundMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MainRouter/RouteInboundMessage',
            grpc__stub__pb2.InboundMessage.SerializeToString,
            grpc__stub__pb2.RoutingAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConnectionManagerStub(object):
    """Implemented by CM workers — receives delivery requests from Main Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeliverOutboundMessage = channel.unary_unary(
                '/ConnectionManager/DeliverOutboundMessage',
                request_serializer=grpc__stub__pb2.OutboundMessage.SerializeToString,
                response_deserializer=grpc__stub__pb2.DeliveryAck.FromString,
                _registered_method=True)


class ConnectionManagerServicer(object):
    """Implemented by CM workers — receives delivery requests from Main Service
    """

    def DeliverOutboundMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeliverOutboundMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverOutboundMessage,
                    request_deserializer=grpc__stub__pb2.OutboundMessage.FromString,
                    response_serializer=grpc__stub__pb2.DeliveryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConnectionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ConnectionManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectionManager(object):
    """Implemented by CM workers — receives delivery requests from Main Service
    """

    @staticmethod
    def DeliverOutboundMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ConnectionManager/DeliverOutboundMessage',
            grpc__stub__pb2.OutboundMessage.SerializeToString,
            grpc__stub__pb2.DeliveryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
