user nginx;
worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 20000;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    
    # This pulls in your watcher.py routing logic
    include /etc/nginx/conf.d/*.conf;
}