# version: '3.8'

services:
  ping-main:
    image: ping-main:1.5
    container_name: ping-main
    ports:
      - "8000:8000"
      - "50050:50050"
    env_file:
      - .env
    environment:
      - SERVICE_GRPC_PORT=50050
      - SERVICE_HTTP_PORT=8000
      - 'CONNECT_ARGS={"statement_cache_size": 0, "prepared_statement_cache_size": 0}'
      - ALGORITHM=HS256
    depends_on:
      - pgbouncer

  ping-cm:
    image: ping-cm:1.5
    container_name: ping-cm
    ports:
      - "8001:8001"
      - "50051:50051"
    env_file:
      - .env
    environment:
      - SERVICE_GRPC_PORT=50051
      - SERVICE_HTTP_PORT=8001
      - ALGORITHM=HS256
    depends_on:
      - ping-main

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    env_file:
      - .env
    environment:
      # Pool Configuration
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=500
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=3
      # Security & Admin
      - ADMIN_USERS=postgres
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro # ro = read-only
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ch9.38%%
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"