server {
    listen 80;
    location = / {
        return 301 /ping/;
    }

    location /ping/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /ping/index.html;
    }

    location /ping/api/ {
        proxy_pass http://ping-main:8000/;
    }

    location /ping/ws/ {
        proxy_pass http://ping-cm:8001/;
    }
}